# Generated by Django 5.0.1 on 2026-02-01 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driveravailability',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Driver Availability', 'verbose_name_plural': 'Driver Availabilities'},
        ),
        migrations.RemoveField(
            model_name='driveravailability',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='driveravailability',
            name='order',
        ),
        migrations.AddField(
            model_name='driveravailability',
            name='manual_override',
            field=models.BooleanField(default=False, help_text='If True, driver manually set availability and auto-scheduling will not override it'),
        ),
        migrations.AddField(
            model_name='driveravailability',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'On Delivery')], default=1),
        ),
        migrations.AlterField(
            model_name='driveravailability',
            name='driver',
            field=models.OneToOneField(limit_choices_to={'role': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='current_availability', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DriverSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='0=Monday, 1=Tuesday, ..., 6=Sunday')),
                ('start_time', models.TimeField(help_text='Start time for this schedule block')),
                ('end_time', models.TimeField(help_text='End time for this schedule block')),
                ('is_active', models.BooleanField(default=True, help_text='Set to False to temporarily disable this schedule without deleting')),
                ('driver', models.ForeignKey(limit_choices_to={'role': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Driver Schedule',
                'verbose_name_plural': 'Driver Schedules',
                'ordering': ['driver__username', 'day_of_week', 'start_time'],
                'indexes': [models.Index(fields=['driver', 'day_of_week', 'is_active'], name='driver_driv_driver__76401b_idx')],
                'unique_together': {('driver', 'day_of_week', 'start_time')},
            },
        ),
    ]
