# Generated by Django 6.0 on 2025-12-29 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('method', models.PositiveSmallIntegerField(choices=[(1, 'Cash on Delivery'), (2, 'Stripe'), (9, 'Other')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Completed'), (2, 'Failed'), (3, 'Refunded')], default=0)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment', to='order.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
