# Generated by Django 6.0 on 2026-01-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Cash on Delivery'), (2, 'Stripe'), (3, 'Cash'), (4, 'MFS'), (5, 'Card'), (9, 'Other')]),
        ),
    ]
