# Generated by Django 5.0.1 on 2026-02-05 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0003_order_order_source_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exported_at', models.DateTimeField(auto_now_add=True)),
                ('resource_type', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dashboard_csv_export_log',
                'ordering': ['-exported_at'],
                'indexes': [models.Index(fields=['user', 'exported_at'], name='dashboard_c_user_id_e2da6d_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.IntegerField()),
                ('to_status', models.IntegerField()),
                ('transitioned_at', models.DateTimeField(auto_now_add=True)),
                ('driver_location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('driver_location_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_backfilled', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statustransitions', to='order.order')),
            ],
            options={
                'db_table': 'dashboard_order_status_transition',
                'ordering': ['transitioned_at'],
                'indexes': [models.Index(fields=['order', 'to_status'], name='dashboard_o_order_i_224582_idx'), models.Index(fields=['transitioned_at'], name='dashboard_o_transit_702256_idx')],
            },
        ),
    ]
