# Generated by Django 5.0.1 on 2026-02-05 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0003_order_order_source_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exported_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when CSV was exported')),
                ('resource_type', models.CharField(help_text="Type of dashboard resource exported (e.g., 'daily_orders', 'driver_performance')", max_length=50)),
                ('user', models.ForeignKey(help_text='User who requested the CSV export', on_delete=django.db.models.deletion.CASCADE, related_name='csv_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CSV Export Log',
                'verbose_name_plural': 'CSV Export Logs',
                'db_table': 'dashboard_csv_export_log',
                'ordering': ['-exported_at'],
                'indexes': [models.Index(fields=['user', 'exported_at'], name='idx_user_exported_at')],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.IntegerField(help_text='Previous order status (1=Pending, 2=Preparing, 3=Ready, 4=Out for Delivery, 5=Delivered, 6=Cancelled, 7=Completed)')),
                ('to_status', models.IntegerField(help_text='New order status (1=Pending, 2=Preparing, 3=Ready, 4=Out for Delivery, 5=Delivered, 6=Cancelled, 7=Completed)')),
                ('transitioned_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when status transition occurred')),
                ('driver_location_lat', models.DecimalField(blank=True, decimal_places=6, help_text="Driver's latitude at time of transition", max_digits=9, null=True)),
                ('driver_location_lon', models.DecimalField(blank=True, decimal_places=6, help_text="Driver's longitude at time of transition", max_digits=9, null=True)),
                ('is_backfilled', models.BooleanField(default=False, help_text='True if this transition was created by backfill command for historical data')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statustransitions', to='order.order')),
            ],
            options={
                'verbose_name': 'Order Status Transition',
                'verbose_name_plural': 'Order Status Transitions',
                'db_table': 'dashboard_order_status_transition',
                'ordering': ['transitioned_at'],
                'indexes': [models.Index(fields=['order', 'to_status'], name='idx_order_to_status'), models.Index(fields=['transitioned_at'], name='idx_transitioned_at')],
            },
        ),
    ]
