# Generated by Django 6.0 on 2026-01-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0003_user_image_user_latitude_user_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Admin'), (1, 'Customer'), (2, 'Restaurant Owner'), (3, 'Driver')], default=1),
        ),
    ]
