# Generated by Django 5.0.1 on 2026-02-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enable_review_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
