# Generated by Django 5.0.1 on 2026-02-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0005_user_enable_review_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe customer ID for subscription billing', max_length=255, null=True),
        ),
    ]
