# Generated by Django 5.0.1 on 2026-02-04 05:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Feature name (e.g., food_ordering, pos_ordering, analytics)', max_length=100, unique=True)),
                ('description', models.TextField(help_text='Description of what this feature provides')),
                ('url_patterns', models.TextField(help_text='URL patterns for this feature (one per line). Use glob patterns like restaurant/*, order/create')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'db_table': 'subscription_features',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Plan name (e.g., Free, Regular, Custom)', max_length=100, unique=True)),
                ('stripe_price_id', models.CharField(blank=True, help_text='Stripe Price ID (null for Free plan)', max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly subscription price in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('duration_days', models.PositiveIntegerField(default=30, help_text='Subscription duration in days (typically 30 for monthly)')),
                ('description', models.TextField(blank=True, help_text='Plan description and benefits')),
                ('grace_period_days', models.PositiveIntegerField(default=3, help_text='Days of grace period after payment failure before downgrading')),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'db_table': 'subscription_plans',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this feature is enabled for this plan')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planfeature_set', to='subscriptions.feature')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planfeature_set', to='subscriptions.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Plan Feature',
                'verbose_name_plural': 'Plan Features',
                'db_table': 'subscription_plan_features',
                'ordering': ['plan', 'feature'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stripe_subscription_id', models.CharField(blank=True, help_text='Stripe subscription ID', max_length=255, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, help_text='Stripe customer ID', max_length=255, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Active'), (1, 'Past Due'), (2, 'Cancelled'), (3, 'Expired')], default=0, help_text='Subscription status')),
                ('current_period_start', models.DateTimeField(blank=True, help_text='Current billing period start', null=True)),
                ('current_period_end', models.DateTimeField(blank=True, help_text='Current billing period end (null for Free plan)', null=True)),
                ('grace_period_end', models.DateTimeField(blank=True, help_text='Grace period end date after payment failure', null=True)),
                ('auto_renew', models.BooleanField(default=True, help_text='Whether subscription auto-renews')),
                ('plan', models.ForeignKey(help_text='Subscription plan', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan')),
                ('user', models.OneToOneField(help_text='Restaurant owner user', limit_choices_to={'role': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
                'db_table': 'user_subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscriptionFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this feature is enabled for this specific user')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersubscriptionfeature_set', to='subscriptions.feature')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersubscriptionfeature_set', to='subscriptions.usersubscription')),
            ],
            options={
                'verbose_name': 'User Subscription Feature Override',
                'verbose_name_plural': 'User Subscription Feature Overrides',
                'db_table': 'subscription_user_features',
                'ordering': ['subscription', 'feature'],
            },
        ),
        migrations.AddConstraint(
            model_name='planfeature',
            constraint=models.UniqueConstraint(fields=('plan', 'feature'), name='unique_plan_feature'),
        ),
        migrations.AddConstraint(
            model_name='usersubscriptionfeature',
            constraint=models.UniqueConstraint(fields=('subscription', 'feature'), name='unique_subscription_feature'),
        ),
    ]
