# Generated by Django 5.0.1 on 2026-02-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='trial_days',
            field=models.PositiveIntegerField(default=0, help_text='Number of days for trial period (0 for no trial)'),
        ),
    ]
