# Generated by Django 6.0 on 2026-01-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderaddon_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_source',
            field=models.IntegerField(choices=[(1, 'Online'), (2, 'POS')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Preparing'), (3, 'Ready for Pickup'), (4, 'Out for Delivery'), (5, 'Delivered'), (6, 'Cancelled'), (7, 'Completed')], default=1),
        ),
    ]
